# Generated by Django 4.2.30 on 2026-08-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistroParametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("lang", models.CharField(max_length=5)),
                ("estrutura", models.CharField(max_length=500)),
                ("eixo", models.CharField(blank=True, max_length=200)),
                ("setor", models.CharField(blank=True, max_length=200)),
                ("nivel", models.CharField(blank=True, max_length=50)),
                ("criterio", models.CharField(blank=True, max_length=500)),
                ("avaliacao", models.CharField(blank=True, max_length=500)),
                ("classificacao", models.CharField(blank=True, max_length=200)),
                ("descritivo", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Parâmetro",
                "verbose_name_plural": "Parâmetros",
                "indexes": [
                    models.Index(fields=["lang", "estrutura"], name="indicadores_lang_90f3ac_idx"),
                    models.Index(fields=["lang", "eixo"], name="indicadores_lang_78fe2d_idx"),
                    models.Index(
                        fields=["lang", "avaliacao", "nivel"], name="indicadores_lang_a35b43_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistroMapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("lang", models.CharField(max_length=5)),
                ("code_muni", models.CharField(blank=True, max_length=20)),
                ("uf", models.CharField(blank=True, max_length=5)),
                ("municipio", models.CharField(blank=True, max_length=200)),
                ("estagio", models.CharField(blank=True, max_length=200)),
                ("perfil", models.CharField(blank=True, max_length=200)),
                ("estimativa_2023_2030", models.FloatField(default=0.0)),
                ("populacao", models.CharField(blank=True, max_length=200)),
                ("empreendimento", models.CharField(blank=True, max_length=500)),
                ("eixo", models.CharField(blank=True, max_length=200)),
                ("modalidade", models.CharField(blank=True, max_length=200)),
                ("tipo_executor", models.CharField(blank=True, max_length=200)),
                ("percentual_executado", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Registro do Mapa",
                "verbose_name_plural": "Registros do Mapa",
                "indexes": [
                    models.Index(fields=["lang", "code_muni"], name="indicadores_lang_a9cf79_idx"),
                    models.Index(fields=["lang", "uf"], name="indicadores_lang_8c5841_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistroFinanciamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("lang", models.CharField(max_length=5)),
                ("programa", models.TextField(blank=True)),
                ("setor", models.CharField(blank=True, max_length=500)),
                ("modalidade", models.CharField(blank=True, max_length=500)),
                ("origem", models.CharField(blank=True, max_length=500)),
                ("valor", models.CharField(blank=True, max_length=500)),
                ("contrapartida", models.CharField(blank=True, max_length=500)),
                ("federal", models.CharField(blank=True, max_length=500)),
                ("estadual", models.CharField(blank=True, max_length=500)),
                ("municipal", models.CharField(blank=True, max_length=500)),
                ("ente", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "Financiamento Climático",
                "verbose_name_plural": "Financiamentos Climáticos",
                "indexes": [
                    models.Index(fields=["lang"], name="indicadores_lang_d71c09_idx"),
                    models.Index(fields=["lang", "setor"], name="indicadores_lang_8de3e5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistroFicha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("lang", models.CharField(max_length=5)),
                ("estrutura", models.CharField(max_length=500)),
                ("eixo", models.CharField(blank=True, max_length=200)),
                ("setor", models.CharField(blank=True, max_length=200)),
                ("link_eixo", models.CharField(blank=True, max_length=2000)),
                ("descricao", models.TextField(blank=True)),
                ("orgao_responsavel", models.TextField(blank=True)),
                ("link_orgao", models.CharField(blank=True, max_length=2000)),
                ("arcabouco_normativo", models.TextField(blank=True)),
                ("link_arcabouco", models.CharField(blank=True, max_length=2000)),
                ("espaco_dialogo_federativo", models.TextField(blank=True)),
                ("financiamento", models.TextField(blank=True)),
                ("periodicidade", models.TextField(blank=True)),
                ("composicao", models.TextField(blank=True)),
                ("carater_decisorio", models.TextField(blank=True)),
                ("politica_plano_relacionado", models.TextField(blank=True)),
                ("contrapartida", models.TextField(blank=True)),
                ("modalidade", models.TextField(blank=True)),
                ("repasse", models.TextField(blank=True)),
                ("fontes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Ficha Técnica",
                "verbose_name_plural": "Fichas Técnicas",
                "indexes": [
                    models.Index(fields=["lang", "estrutura"], name="indicadores_lang_d3e3e8_idx"),
                    models.Index(fields=["lang", "eixo"], name="indicadores_lang_63c960_idx"),
                ],
            },
        ),
    ]
